name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
version: 1.0.2
homepage: https://github.com/LuisThein
repository: https://github.com/LuisThein/platform_maps_flutter
issue_tracker: https://github.com/LuisThein/platform_maps_flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter:
    git:
      url: https://github.com/felixjunghans/google_maps_flutter.git
      ref: main
      path: ./google_maps_flutter
  google_maps_flutter_platform_interface:
    git:
      url: https://github.com/felixjunghans/google_maps_flutter.git
      ref: main
      path: ./google_maps_flutter_platform_interface
  apple_maps_flutter:
    git:
      url: https://github.com/felixjunghans/apple_maps_flutter.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
